version: "3.9"

services:
  indexer_db:
    container_name: indexer_db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - indexer_db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]

  indexer_processor:
    container_name: indexer_processor
    restart: unless-stopped
    build:
      context: .
      target: processor
    depends_on:
      - indexer_db

  indexer_graphql:
    container_name: indexer_graphql
    restart: unless-stopped
    build:
      context: .
      target: query-node
    ports:
      - "4467:4347"
    depends_on:
      - indexer_db
      - indexer_processor

  archive_db:
    container_name: archive_db
    image: cockroachdb/cockroach:v22.2.2
    restart: unless-stopped
    volumes:
      - archive_db:/cockroach/cockroach-data
    ports:
      - "26257:26257"
    command: [
      "start-single-node",
      "--insecure"
    ]

  archive_ingest:
    container_name: archive_ingest
    image: subsquid/substrate-ingest:latest
    restart: unless-stopped
    depends_on:
      - archive_db
    command: [
      "-e", "wss://rpc.parachain.efinitystaging.com",
      "-c", "40",
      "--out", "postgres://root@archive_db:26257/defaultdb"
    ]

  archive_gateway:
    container_name: archive_gateway
    image: subsquid/substrate-gateway:firesquid
    restart: unless-stopped
    depends_on:
      - archive_db
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [
      "--database-url", "postgres://root@archive_db:26257/defaultdb",
    ]
    ports:
      - "8888:8000"

  archive_explorer:
    container_name: archive_explorer
    image: subsquid/substrate-explorer:latest
    restart: unless-stopped
    environment:
      DB_TYPE: cockroach
      DB_HOST: archive_db
      DB_PORT: "26257"
      DB_NAME: "defaultdb"
      DB_USER: "root"
    ports:
      - "4444:3000"

volumes:
  indexer_db:
  archive_db:
