version: "3.9"

services:
  indexer_db:
    container_name: indexer_db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - indexer_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: [
      "postgres",
      "-c", "max_connections=200"
    ]

  indexer_redis:
    container_name: indexer_redis
    image: redis:7.0
    restart: on-failure
    volumes:
      - redis_db:/data
    ports:
      - "6389:6379"

  indexer_processor:
    container_name: indexer_processor
    restart: unless-stopped
    image: ghcr.io/efinity/indexer:${VERSION:-latest}
    environment:
      CONTAINER_ROLE: processor
    build:
      context: .
    volumes:
      - .env:/squid/.env
    depends_on:
      - indexer_db
      - indexer_worker

  indexer_graphql:
    container_name: indexer_graphql
    restart: unless-stopped
    image: ghcr.io/efinity/indexer:${VERSION:-latest}
    environment:
      CONTAINER_ROLE: graphql
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - .env:/squid/.env
    depends_on:
      - indexer_db
      - indexer_processor

  indexer_worker:
    container_name: indexer_worker
    restart: unless-stopped
    image: ghcr.io/efinity/indexer:${VERSION:-latest}
    environment:
      CONTAINER_ROLE: worker
    build:
      context: .
    ports:
      - "9090:9090"
    volumes:
      - .env:/squid/.env
    depends_on:
      - indexer_db
      - indexer_redis

  archive_db:
    container_name: archive_db
    image: cockroachdb/cockroach:v22.2.2
    restart: unless-stopped
    volumes:
      - archive_db:/cockroach/cockroach-data
    ports:
      - "26257:26257"
    command: [
      "start-single-node",
      "--insecure"
    ]

  archive_ingest:
    container_name: archive_ingest
    image: subsquid/substrate-ingest:latest
    restart: unless-stopped
    depends_on:
      - archive_db
    command: [
      "-e", "wss://archive.matrix.blockchain.enjin.io",
      "-c", "40",
      "--out", "postgres://root@archive_db:26257/defaultdb"
    ]

  archive_gateway:
    container_name: archive_gateway
    image: subsquid/substrate-gateway:firesquid
    restart: unless-stopped
    depends_on:
      - archive_db
    environment:
      DATABASE_MAX_CONNECTIONS: 10
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [
      "--database-url", "postgres://root@archive_db:26257/defaultdb",
      "--scan-start-value", "100"
    ]
    ports:
      - "8888:8000"

  archive_explorer:
    container_name: archive_explorer
    image: subsquid/substrate-explorer:latest
    restart: unless-stopped
    environment:
      DB_TYPE: cockroach
      DB_HOST: archive_db
      DB_PORT: "26257"
      DB_NAME: "defaultdb"
      DB_USER: "root"
    ports:
      - "4444:3000"

volumes:
  indexer_db:
  archive_db:
  redis_db:
  
