name: Snyk
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
